import type { Metric } from "./metric-types";

// Helper to generate mock time-series for Nov 1-16, 2019
function genSeries(base: number, variance: number): { date: string; value: number }[] {
  return Array.from({ length: 16 }, (_, i) => ({
    date: `2019-11-${String(i + 1).padStart(2, "0")}`,
    value: Math.round(base + (Math.random() - 0.5) * 2 * variance),
  }));
}

export const PRESEEDED_METRICS: Metric[] = [
  // ── Acquisition ──
  {
    id: "m-dau",
    name: "Daily Active Users (DAU)",
    description: "Unique users who triggered at least one event per day",
    type: "kpi",
    category: "Acquisition",
    status: "healthy",
    value: 147500,
    valueFormat: "integer",
    changePercent: 3.2,
    aggregation: "unique_count",
    table: "daily_metrics",
    column: "unique_users",
    timeColumn: "date",
    formula: "COUNT(DISTINCT user_id)",
    sql: "SELECT date, unique_users AS value\nFROM daily_metrics\nORDER BY date",
    dimensions: ["brand", "category_code"],
    timeGrain: "daily",
    granularity: "Store-level",
    slices: ["brand", "category_code", "event_type"],
    relationships: [
      { metricId: "m-sessions", metricName: "Total Sessions", direction: "drives", type: "component" },
      { metricId: "m-arpu", metricName: "ARPU", direction: "drives", type: "component" },
      { metricId: "m-conversion", metricName: "Conversion Rate", direction: "drives", type: "influence" },
    ],
    owner: "Analytics Team",
    ownerInitials: "AT",
    createdAt: "2024-11-01",
    updatedAt: "2024-11-10",
    version: 1,
    errors: 0,
    timeSeries: genSeries(147500, 12000),
  },
  {
    id: "m-sessions",
    name: "Total Sessions",
    description: "Total number of unique user sessions per day",
    type: "indicator",
    category: "Acquisition",
    status: "healthy",
    value: 218400,
    valueFormat: "integer",
    changePercent: 1.8,
    aggregation: "sum",
    table: "daily_metrics",
    column: "total_sessions",
    timeColumn: "date",
    formula: "SUM(total_sessions)",
    sql: "SELECT date, total_sessions AS value\nFROM daily_metrics\nORDER BY date",
    dimensions: [],
    timeGrain: "daily",
    granularity: "Store-level",
    relationships: [
      { metricId: "m-dau", metricName: "DAU", direction: "driven_by", type: "component" },
      { metricId: "m-rev-per-session", metricName: "Revenue per Session", direction: "drives", type: "component" },
    ],
    owner: "Analytics Team",
    ownerInitials: "AT",
    createdAt: "2024-11-01",
    updatedAt: "2024-11-10",
    version: 1,
    errors: 0,
    timeSeries: genSeries(218400, 18000),
  },
  {
    id: "m-new-users",
    name: "New Users",
    description: "Users appearing for the first time in the dataset",
    type: "diagnostic",
    category: "Acquisition",
    status: "partial",
    value: 42300,
    valueFormat: "integer",
    changePercent: -2.1,
    aggregation: "count",
    table: "events",
    column: "user_id",
    timeColumn: "event_time",
    formula: "COUNT(DISTINCT user_id) WHERE first_seen = date",
    sql: "WITH first_seen AS (\n  SELECT user_id, MIN(CAST(event_time AS DATE)) AS first_date\n  FROM events\n  GROUP BY user_id\n)\nSELECT first_date AS date, COUNT(*) AS value\nFROM first_seen\nGROUP BY first_date\nORDER BY first_date",
    dimensions: [],
    timeGrain: "daily",
    granularity: "Store-level",
    relationships: [
      { metricId: "m-dau", metricName: "DAU", direction: "drives", type: "component" },
    ],
    owner: "Growth Team",
    ownerInitials: "GT",
    createdAt: "2024-11-02",
    updatedAt: "2024-11-10",
    version: 1,
    errors: 1,
    timeSeries: genSeries(42300, 5000),
  },

  // ── Engagement ──
  {
    id: "m-pageviews",
    name: "Page Views",
    description: "Total product page view events per day",
    type: "kpi",
    category: "Engagement",
    status: "healthy",
    value: 1850000,
    valueFormat: "integer",
    changePercent: 5.4,
    aggregation: "sum",
    table: "daily_metrics",
    column: "views",
    timeColumn: "date",
    formula: "SUM(views)",
    sql: "SELECT date, views AS value\nFROM daily_metrics\nORDER BY date",
    dimensions: ["brand", "category_code"],
    timeGrain: "daily",
    granularity: "Store-level",
    slices: ["brand", "category_code"],
    relationships: [
      { metricId: "m-conversion", metricName: "Conversion Rate", direction: "drives", type: "component" },
      { metricId: "m-add-to-cart", metricName: "Add-to-Cart Events", direction: "drives", type: "influence" },
    ],
    owner: "Product Team",
    ownerInitials: "PT",
    createdAt: "2024-11-01",
    updatedAt: "2024-11-10",
    version: 1,
    errors: 0,
    timeSeries: genSeries(1850000, 150000),
  },
  {
    id: "m-add-to-cart",
    name: "Add-to-Cart Events",
    description: "Number of add-to-cart actions per day",
    type: "indicator",
    category: "Engagement",
    status: "healthy",
    value: 295000,
    valueFormat: "integer",
    changePercent: 2.7,
    aggregation: "sum",
    table: "daily_metrics",
    column: "add_to_carts",
    timeColumn: "date",
    formula: "SUM(add_to_carts)",
    sql: "SELECT date, add_to_carts AS value\nFROM daily_metrics\nORDER BY date",
    dimensions: ["brand", "category_code"],
    timeGrain: "daily",
    granularity: "Store-level",
    relationships: [
      { metricId: "m-pageviews", metricName: "Page Views", direction: "driven_by", type: "influence" },
      { metricId: "m-cart-abandon", metricName: "Cart Abandonment Rate", direction: "drives", type: "component" },
    ],
    owner: "Product Team",
    ownerInitials: "PT",
    createdAt: "2024-11-01",
    updatedAt: "2024-11-10",
    version: 1,
    errors: 0,
    timeSeries: genSeries(295000, 25000),
  },
  {
    id: "m-cart-removals",
    name: "Cart Removals",
    description: "Number of remove-from-cart actions per day",
    type: "diagnostic",
    category: "Engagement",
    status: "healthy",
    value: 182000,
    valueFormat: "integer",
    changePercent: -1.3,
    aggregation: "sum",
    table: "daily_metrics",
    column: "removes",
    timeColumn: "date",
    formula: "SUM(removes)",
    sql: "SELECT date, removes AS value\nFROM daily_metrics\nORDER BY date",
    dimensions: [],
    timeGrain: "daily",
    granularity: "Store-level",
    relationships: [
      { metricId: "m-cart-abandon", metricName: "Cart Abandonment Rate", direction: "drives", type: "component" },
    ],
    owner: "Product Team",
    ownerInitials: "PT",
    createdAt: "2024-11-01",
    updatedAt: "2024-11-10",
    version: 1,
    errors: 0,
    timeSeries: genSeries(182000, 15000),
  },
  {
    id: "m-cart-abandon",
    name: "Cart Abandonment Rate",
    description: "Percentage of add-to-cart events that don't convert to purchase",
    type: "diagnostic",
    category: "Engagement",
    status: "healthy",
    value: 67.8,
    valueFormat: "percent",
    changePercent: -0.5,
    aggregation: "derived_ratio",
    table: "daily_metrics",
    column: "add_to_carts",
    timeColumn: "date",
    formula: "(add_to_carts - purchases) / add_to_carts * 100",
    sql: "SELECT date,\n  ROUND((add_to_carts - purchases)::FLOAT / NULLIF(add_to_carts, 0) * 100, 2) AS value\nFROM daily_metrics\nORDER BY date",
    dimensions: [],
    timeGrain: "daily",
    granularity: "Store-level",
    relationships: [
      { metricId: "m-add-to-cart", metricName: "Add-to-Cart Events", direction: "driven_by", type: "component" },
      { metricId: "m-purchases", metricName: "Total Purchases", direction: "driven_by", type: "component" },
    ],
    owner: "Product Team",
    ownerInitials: "PT",
    createdAt: "2024-11-02",
    updatedAt: "2024-11-10",
    version: 1,
    errors: 0,
    timeSeries: genSeries(67.8, 3),
  },

  // ── Revenue ──
  {
    id: "m-revenue",
    name: "Total Revenue",
    description: "Sum of all purchase transaction values per day",
    type: "kpi",
    category: "Revenue",
    status: "healthy",
    value: 7206250,
    valueFormat: "currency",
    changePercent: 4.8,
    aggregation: "sum",
    table: "daily_metrics",
    column: "revenue",
    timeColumn: "date",
    formula: "SUM(revenue)",
    sql: "SELECT date, revenue AS value\nFROM daily_metrics\nORDER BY date",
    dimensions: ["brand", "category_code"],
    timeGrain: "daily",
    granularity: "Store-level",
    slices: ["brand", "category_code"],
    relationships: [
      { metricId: "m-aov", metricName: "AOV", direction: "driven_by", type: "component" },
      { metricId: "m-purchases", metricName: "Total Purchases", direction: "driven_by", type: "component" },
      { metricId: "m-arpu", metricName: "ARPU", direction: "drives", type: "component" },
    ],
    owner: "Revenue Team",
    ownerInitials: "RT",
    createdAt: "2024-11-01",
    updatedAt: "2024-11-10",
    version: 2,
    errors: 0,
    timeSeries: genSeries(7206250, 800000),
  },
  {
    id: "m-purchases",
    name: "Total Purchases",
    description: "Number of completed purchase events per day",
    type: "indicator",
    category: "Revenue",
    status: "healthy",
    value: 42100,
    valueFormat: "integer",
    changePercent: 2.1,
    aggregation: "sum",
    table: "daily_metrics",
    column: "purchases",
    timeColumn: "date",
    formula: "SUM(purchases)",
    sql: "SELECT date, purchases AS value\nFROM daily_metrics\nORDER BY date",
    dimensions: ["brand", "category_code"],
    timeGrain: "daily",
    granularity: "Store-level",
    relationships: [
      { metricId: "m-revenue", metricName: "Total Revenue", direction: "drives", type: "component" },
      { metricId: "m-aov", metricName: "AOV", direction: "drives", type: "component" },
      { metricId: "m-conversion", metricName: "Conversion Rate", direction: "drives", type: "component" },
    ],
    owner: "Revenue Team",
    ownerInitials: "RT",
    createdAt: "2024-11-01",
    updatedAt: "2024-11-10",
    version: 1,
    errors: 0,
    timeSeries: genSeries(42100, 4000),
  },
  {
    id: "m-aov",
    name: "Average Order Value (AOV)",
    description: "Average revenue per purchase transaction",
    type: "kpi",
    category: "Revenue",
    status: "healthy",
    value: 171.17,
    valueFormat: "currency",
    changePercent: 2.6,
    aggregation: "derived_ratio",
    table: "daily_metrics",
    column: "revenue",
    timeColumn: "date",
    formula: "SUM(revenue) / SUM(purchases)",
    sql: "SELECT date,\n  ROUND(revenue::FLOAT / NULLIF(purchases, 0), 2) AS value\nFROM daily_metrics\nORDER BY date",
    dimensions: ["brand", "category_code"],
    timeGrain: "daily",
    granularity: "Store-level",
    relationships: [
      { metricId: "m-revenue", metricName: "Total Revenue", direction: "drives", type: "component" },
      { metricId: "m-purchases", metricName: "Total Purchases", direction: "driven_by", type: "component" },
    ],
    owner: "Revenue Team",
    ownerInitials: "RT",
    createdAt: "2024-11-01",
    updatedAt: "2024-11-10",
    version: 1,
    errors: 0,
    timeSeries: genSeries(171.17, 15),
  },
  {
    id: "m-rev-per-session",
    name: "Revenue per Session",
    description: "Average revenue generated per user session",
    type: "diagnostic",
    category: "Revenue",
    status: "healthy",
    value: 33.0,
    valueFormat: "currency",
    changePercent: 1.2,
    aggregation: "derived_ratio",
    table: "daily_metrics",
    column: "revenue",
    timeColumn: "date",
    formula: "SUM(revenue) / SUM(total_sessions)",
    sql: "SELECT date,\n  ROUND(revenue::FLOAT / NULLIF(total_sessions, 0), 2) AS value\nFROM daily_metrics\nORDER BY date",
    dimensions: [],
    timeGrain: "daily",
    granularity: "Store-level",
    relationships: [
      { metricId: "m-revenue", metricName: "Total Revenue", direction: "driven_by", type: "component" },
      { metricId: "m-sessions", metricName: "Total Sessions", direction: "driven_by", type: "component" },
    ],
    owner: "Revenue Team",
    ownerInitials: "RT",
    createdAt: "2024-11-02",
    updatedAt: "2024-11-10",
    version: 1,
    errors: 0,
    timeSeries: genSeries(33.0, 4),
  },
  {
    id: "m-brand-revenue",
    name: "Top Brand Revenue",
    description: "Revenue aggregated by brand",
    type: "diagnostic",
    category: "Revenue",
    status: "healthy",
    value: 28500000,
    valueFormat: "currency",
    changePercent: 3.4,
    aggregation: "sum",
    table: "brand_metrics",
    column: "total_revenue",
    timeColumn: "date",
    formula: "SUM(total_revenue) GROUP BY brand",
    sql: "SELECT brand, total_revenue AS value\nFROM brand_metrics\nORDER BY total_revenue DESC\nLIMIT 20",
    dimensions: ["brand"],
    timeGrain: "daily",
    granularity: "Brand-level",
    relationships: [
      { metricId: "m-revenue", metricName: "Total Revenue", direction: "drives", type: "component" },
    ],
    owner: "Revenue Team",
    ownerInitials: "RT",
    createdAt: "2024-11-02",
    updatedAt: "2024-11-10",
    version: 1,
    errors: 0,
    timeSeries: genSeries(28500000, 3000000),
  },
  {
    id: "m-category-revenue",
    name: "Top Category Revenue",
    description: "Revenue aggregated by product category",
    type: "diagnostic",
    category: "Revenue",
    status: "healthy",
    value: 35200000,
    valueFormat: "currency",
    changePercent: 2.9,
    aggregation: "sum",
    table: "category_metrics",
    column: "total_revenue",
    timeColumn: "date",
    formula: "SUM(total_revenue) GROUP BY category_code",
    sql: "SELECT category_code, total_revenue AS value\nFROM category_metrics\nORDER BY total_revenue DESC\nLIMIT 20",
    dimensions: ["category_code"],
    timeGrain: "daily",
    granularity: "Category-level",
    relationships: [
      { metricId: "m-revenue", metricName: "Total Revenue", direction: "drives", type: "component" },
    ],
    owner: "Revenue Team",
    ownerInitials: "RT",
    createdAt: "2024-11-02",
    updatedAt: "2024-11-10",
    version: 1,
    errors: 0,
    timeSeries: genSeries(35200000, 4000000),
  },

  // ── Monetization ──
  {
    id: "m-conversion",
    name: "Conversion Rate",
    description: "Percentage of page views that result in a purchase",
    type: "kpi",
    category: "Monetization",
    status: "healthy",
    value: 2.27,
    valueFormat: "percent",
    changePercent: 0.3,
    aggregation: "derived_ratio",
    table: "daily_metrics",
    column: "purchases",
    timeColumn: "date",
    formula: "SUM(purchases) / SUM(views) * 100",
    sql: "SELECT date,\n  ROUND(purchases::FLOAT / NULLIF(views, 0) * 100, 2) AS value\nFROM daily_metrics\nORDER BY date",
    dimensions: ["brand", "category_code"],
    timeGrain: "daily",
    granularity: "Store-level",
    relationships: [
      { metricId: "m-purchases", metricName: "Total Purchases", direction: "driven_by", type: "component" },
      { metricId: "m-pageviews", metricName: "Page Views", direction: "driven_by", type: "component" },
      { metricId: "m-paying-users", metricName: "Paying Users", direction: "drives", type: "influence" },
    ],
    owner: "Growth Team",
    ownerInitials: "GT",
    createdAt: "2024-11-01",
    updatedAt: "2024-11-10",
    version: 1,
    errors: 0,
    timeSeries: genSeries(2.27, 0.3),
  },
  {
    id: "m-paying-users",
    name: "Paying Users",
    description: "Number of unique users who made at least one purchase per day",
    type: "indicator",
    category: "Monetization",
    status: "healthy",
    value: 13192,
    valueFormat: "integer",
    changePercent: 1.5,
    aggregation: "sum",
    table: "daily_metrics",
    column: "paying_users",
    timeColumn: "date",
    formula: "SUM(paying_users)",
    sql: "SELECT date, paying_users AS value\nFROM daily_metrics\nORDER BY date",
    dimensions: [],
    timeGrain: "daily",
    granularity: "Store-level",
    relationships: [
      { metricId: "m-conversion", metricName: "Conversion Rate", direction: "driven_by", type: "influence" },
      { metricId: "m-arppu", metricName: "ARPPU", direction: "drives", type: "component" },
    ],
    owner: "Growth Team",
    ownerInitials: "GT",
    createdAt: "2024-11-01",
    updatedAt: "2024-11-10",
    version: 1,
    errors: 0,
    timeSeries: genSeries(13192, 1200),
  },
  {
    id: "m-arpu",
    name: "ARPU",
    description: "Average revenue per unique user per day",
    type: "kpi",
    category: "Monetization",
    status: "healthy",
    value: 48.86,
    valueFormat: "currency",
    changePercent: 1.6,
    aggregation: "derived_ratio",
    table: "daily_metrics",
    column: "revenue",
    timeColumn: "date",
    formula: "SUM(revenue) / SUM(unique_users)",
    sql: "SELECT date,\n  ROUND(revenue::FLOAT / NULLIF(unique_users, 0), 2) AS value\nFROM daily_metrics\nORDER BY date",
    dimensions: [],
    timeGrain: "daily",
    granularity: "Store-level",
    relationships: [
      { metricId: "m-revenue", metricName: "Total Revenue", direction: "driven_by", type: "component" },
      { metricId: "m-dau", metricName: "DAU", direction: "driven_by", type: "component" },
    ],
    owner: "Revenue Team",
    ownerInitials: "RT",
    createdAt: "2024-11-01",
    updatedAt: "2024-11-10",
    version: 1,
    errors: 0,
    timeSeries: genSeries(48.86, 5),
  },
  {
    id: "m-arppu",
    name: "ARPPU",
    description: "Average revenue per paying user per day",
    type: "diagnostic",
    category: "Monetization",
    status: "healthy",
    value: 546.27,
    valueFormat: "currency",
    changePercent: 3.1,
    aggregation: "derived_ratio",
    table: "daily_metrics",
    column: "revenue",
    timeColumn: "date",
    formula: "SUM(revenue) / SUM(paying_users)",
    sql: "SELECT date,\n  ROUND(revenue::FLOAT / NULLIF(paying_users, 0), 2) AS value\nFROM daily_metrics\nORDER BY date",
    dimensions: [],
    timeGrain: "daily",
    granularity: "Store-level",
    relationships: [
      { metricId: "m-revenue", metricName: "Total Revenue", direction: "driven_by", type: "component" },
      { metricId: "m-paying-users", metricName: "Paying Users", direction: "driven_by", type: "component" },
    ],
    owner: "Revenue Team",
    ownerInitials: "RT",
    createdAt: "2024-11-02",
    updatedAt: "2024-11-10",
    version: 1,
    errors: 0,
    timeSeries: genSeries(546.27, 50),
  },
  {
    id: "m-avg-purchase-price",
    name: "Avg Purchase Price",
    description: "Average transaction price across all brands",
    type: "index",
    category: "Monetization",
    status: "enrichment_needed",
    value: 135.42,
    valueFormat: "currency",
    changePercent: 0.8,
    aggregation: "derived_ratio",
    table: "brand_metrics",
    column: "avg_purchase_price",
    timeColumn: "date",
    formula: "AVG(avg_purchase_price)",
    sql: "SELECT brand,\n  ROUND(total_revenue::FLOAT / NULLIF(purchases, 0), 2) AS value\nFROM brand_metrics\nWHERE purchases > 0\nORDER BY value DESC",
    dimensions: ["brand"],
    timeGrain: "daily",
    granularity: "Brand-level",
    relationships: [
      { metricId: "m-aov", metricName: "AOV", direction: "drives", type: "influence" },
    ],
    owner: "Analytics Team",
    ownerInitials: "AT",
    createdAt: "2024-11-03",
    updatedAt: "2024-11-10",
    version: 1,
    errors: 2,
    timeSeries: genSeries(135.42, 12),
  },
];
