import type {
  SKU,
  Transaction,
  Player,
  StoreKPI,
  RevenueDataPoint,
  Offer,
  Campaign,
} from "./store-types";

// ── Helper: generate dates relative to "today" ──

/** Generate 14-day daily revenue array. Distributes total revenue with realistic noise. */
function dailyRevenue(total: number, trend: "up" | "down" | "flat" | "spike" = "flat"): number[] {
  if (total === 0) return Array(14).fill(0);
  const days = 14;
  const base = total / days;
  return Array.from({ length: days }, (_, i) => {
    const noise = 0.5 + Math.random();
    let multiplier = noise;
    if (trend === "up") multiplier = noise * (0.5 + (i / days) * 1.2);
    else if (trend === "down") multiplier = noise * (1.2 - (i / days) * 0.8);
    else if (trend === "spike") multiplier = i >= 9 && i <= 11 ? noise * 2.5 : noise * 0.6;
    return Math.round(base * multiplier * 100) / 100;
  });
}

function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString().split("T")[0];
}

function daysAgoISO(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  d.setHours(
    Math.floor(Math.random() * 14) + 8,
    Math.floor(Math.random() * 60),
    Math.floor(Math.random() * 60)
  );
  return d.toISOString();
}

// ── SKUs (15 items) ──

export const MOCK_SKUS: SKU[] = [
  {
    id: "sku-gems-100",
    name: "100 Gems",
    description: "A small pouch of gems to get you started.",
    type: "consumable",
    status: "active",
    basePrice: 0.99,
    currency: "USD",
    territoryPricing: [
      { territory: "EU", price: 0.99, currency: "EUR" },
      { territory: "JP", price: 120, currency: "JPY" },
    ],
    discounts: [],
    trackInventory: false,
    limitPerUser: false,
    tags: ["gems", "starter"],
    createdAt: "2025-06-15",
    lastModified: "2025-12-01",
  },
  {
    id: "sku-gems-500",
    name: "500 Gems",
    description: "A generous bag of gems for regular players.",
    type: "consumable",
    status: "active",
    basePrice: 4.99,
    currency: "USD",
    territoryPricing: [
      { territory: "EU", price: 4.49, currency: "EUR" },
      { territory: "JP", price: 600, currency: "JPY" },
      { territory: "BR", price: 19.9, currency: "BRL" },
    ],
    discounts: [],
    trackInventory: false,
    limitPerUser: false,
    tags: ["gems", "popular"],
    badge: "Most Popular",
    createdAt: "2025-06-15",
    lastModified: "2025-12-10",
  },
  {
    id: "sku-gems-1200",
    name: "1,200 Gems",
    description: "A treasure chest packed with gems. Best value for mid-spenders.",
    type: "consumable",
    status: "active",
    basePrice: 9.99,
    currency: "USD",
    territoryPricing: [
      { territory: "EU", price: 9.49, currency: "EUR" },
      { territory: "JP", price: 1200, currency: "JPY" },
    ],
    discounts: [
      {
        id: "disc-1",
        type: "percentage",
        value: 10,
        startDate: daysAgo(5),
        endDate: daysAgo(-10),
        badge: "SALE",
      },
    ],
    trackInventory: false,
    limitPerUser: false,
    tags: ["gems", "best-value"],
    badge: "Best Value",
    createdAt: "2025-06-15",
    lastModified: daysAgo(5),
  },
  {
    id: "sku-gems-3000",
    name: "3,000 Gems",
    description: "The ultimate gem haul for whales and power players.",
    type: "consumable",
    status: "active",
    basePrice: 19.99,
    currency: "USD",
    territoryPricing: [
      { territory: "EU", price: 18.99, currency: "EUR" },
      { territory: "JP", price: 2400, currency: "JPY" },
      { territory: "IN", price: 1499, currency: "INR" },
    ],
    discounts: [],
    trackInventory: false,
    limitPerUser: false,
    tags: ["gems", "whale"],
    createdAt: "2025-06-15",
    lastModified: "2025-11-20",
  },
  {
    id: "sku-bp-standard",
    name: "Season 12 Battle Pass",
    description: "Unlock 50 tiers of rewards, skins, and exclusive items this season.",
    type: "non_consumable",
    status: "active",
    basePrice: 9.99,
    currency: "USD",
    territoryPricing: [
      { territory: "EU", price: 9.99, currency: "EUR" },
    ],
    discounts: [],
    trackInventory: false,
    limitPerUser: true,
    purchaseLimit: 1,
    tags: ["battle-pass", "seasonal"],
    effectiveDate: "2026-01-01",
    expirationDate: "2026-03-31",
    createdAt: "2025-12-20",
    lastModified: "2026-01-02",
  },
  {
    id: "sku-bp-premium",
    name: "Premium Battle Pass",
    description: "Battle Pass + 25 tier skips + exclusive legendary skin.",
    type: "non_consumable",
    status: "active",
    basePrice: 19.99,
    currency: "USD",
    territoryPricing: [],
    discounts: [],
    trackInventory: false,
    limitPerUser: true,
    purchaseLimit: 1,
    tags: ["battle-pass", "premium"],
    effectiveDate: "2026-01-01",
    expirationDate: "2026-03-31",
    createdAt: "2025-12-20",
    lastModified: "2026-01-02",
  },
  {
    id: "sku-starter-bundle",
    name: "Starter Bundle",
    description: "500 gems + rare weapon + 3-day XP boost. One-time offer for new players.",
    type: "non_consumable",
    status: "active",
    basePrice: 2.99,
    currency: "USD",
    territoryPricing: [
      { territory: "IN", price: 199, currency: "INR" },
    ],
    discounts: [],
    trackInventory: false,
    limitPerUser: true,
    purchaseLimit: 1,
    tags: ["bundle", "starter", "one-time"],
    contents: [
      { skuId: "sku-gems-500", skuName: "500 Gems", quantity: 1 },
      { skuId: "sku-dragon-skin", skuName: "Dragon Skin", quantity: 1 },
    ],
    createdAt: "2025-08-01",
    lastModified: "2025-11-15",
  },
  {
    id: "sku-warrior-pack",
    name: "Warrior Starter Pack",
    description: "1,000 gems + warrior armor set + 7-day VIP trial.",
    type: "non_consumable",
    status: "active",
    basePrice: 7.99,
    currency: "USD",
    territoryPricing: [],
    discounts: [],
    trackInventory: false,
    limitPerUser: true,
    purchaseLimit: 1,
    tags: ["bundle", "warrior"],
    contents: [
      { skuId: "sku-gems-1200", skuName: "1,200 Gems", quantity: 1 },
    ],
    createdAt: "2025-09-10",
    lastModified: "2025-12-05",
  },
  {
    id: "sku-vip-monthly",
    name: "VIP Monthly",
    description: "Daily gem drops, ad-free play, and exclusive monthly cosmetic.",
    type: "subscription",
    status: "active",
    basePrice: 4.99,
    currency: "USD",
    territoryPricing: [
      { territory: "EU", price: 4.99, currency: "EUR" },
      { territory: "JP", price: 600, currency: "JPY" },
    ],
    discounts: [],
    renewalPeriodDays: 30,
    trackInventory: false,
    limitPerUser: false,
    tags: ["subscription", "vip"],
    createdAt: "2025-07-01",
    lastModified: "2025-12-01",
  },
  {
    id: "sku-gold-weekly",
    name: "Gold Pass Weekly",
    description: "Weekly gold rush: 200 gems + double rewards for 7 days.",
    type: "subscription",
    status: "active",
    basePrice: 1.99,
    currency: "USD",
    territoryPricing: [],
    discounts: [],
    renewalPeriodDays: 7,
    trackInventory: false,
    limitPerUser: false,
    tags: ["subscription", "gold"],
    createdAt: "2025-10-01",
    lastModified: "2025-12-15",
  },
  {
    id: "sku-dragon-skin",
    name: "Dragon Skin",
    description: "Legendary dragon armor skin with fire trail effect.",
    type: "non_consumable",
    status: "active",
    basePrice: 3.99,
    currency: "USD",
    territoryPricing: [],
    discounts: [],
    trackInventory: true,
    inventoryCount: 500,
    limitPerUser: true,
    purchaseLimit: 1,
    tags: ["cosmetic", "legendary"],
    createdAt: "2025-11-01",
    lastModified: "2025-12-20",
  },
  {
    id: "sku-neon-shield",
    name: "Neon Shield",
    description: "Glowing neon shield with pulsing energy effect.",
    type: "non_consumable",
    status: "active",
    basePrice: 2.49,
    currency: "USD",
    territoryPricing: [],
    discounts: [],
    trackInventory: false,
    limitPerUser: false,
    tags: ["cosmetic", "shield"],
    createdAt: "2025-10-15",
    lastModified: "2025-11-30",
  },
  {
    id: "sku-shadow-wings",
    name: "Shadow Wings",
    description: "Dark ethereal wings with particle shadow trail.",
    type: "non_consumable",
    status: "active",
    basePrice: 5.99,
    currency: "USD",
    territoryPricing: [],
    discounts: [],
    trackInventory: true,
    inventoryCount: 200,
    limitPerUser: true,
    purchaseLimit: 1,
    tags: ["cosmetic", "wings", "limited"],
    badge: "Limited",
    createdAt: "2025-11-20",
    lastModified: daysAgo(3),
  },
  {
    id: "sku-holiday-bundle",
    name: "Holiday Bundle 2026",
    description: "5,000 gems + holiday skin set + snowflake trail. Coming soon.",
    type: "non_consumable",
    status: "draft",
    basePrice: 14.99,
    currency: "USD",
    territoryPricing: [
      { territory: "EU", price: 13.99, currency: "EUR" },
    ],
    discounts: [],
    trackInventory: true,
    inventoryCount: 1000,
    limitPerUser: true,
    purchaseLimit: 1,
    tags: ["bundle", "holiday", "seasonal"],
    contents: [
      { skuId: "sku-gems-3000", skuName: "3,000 Gems", quantity: 1 },
      { skuId: "sku-shadow-wings", skuName: "Shadow Wings", quantity: 1 },
    ],
    effectiveDate: "2026-12-15",
    expirationDate: "2027-01-05",
    createdAt: daysAgo(10),
    lastModified: daysAgo(2),
  },
  {
    id: "sku-mystery-box",
    name: "Mystery Box",
    description: "Random reward: gems, skins, or XP boosts. Luck favors the bold.",
    type: "consumable",
    status: "active",
    basePrice: 1.99,
    currency: "USD",
    territoryPricing: [],
    discounts: [],
    trackInventory: false,
    limitPerUser: true,
    purchaseLimit: 3,
    tags: ["mystery", "random", "fun"],
    createdAt: "2025-09-01",
    lastModified: "2025-12-18",
  },
];

// ── Players (20) ──

export const MOCK_PLAYERS: Player[] = [
  {
    id: "player-001",
    name: "DragonSlayer99",
    email: "dragon99@game.io",
    status: "active",
    ltv: 2412.5,
    aov: 48.25,
    purchaseCount: 50,
    firstPurchaseAt: "2025-07-12",
    lastActiveAt: daysAgo(0),
    createdAt: "2025-06-20",
    country: "US",
    topItems: [
      { skuId: "sku-gems-3000", skuName: "3,000 Gems", count: 18, totalSpent: 359.82 },
      { skuId: "sku-vip-monthly", skuName: "VIP Monthly", count: 8, totalSpent: 39.92 },
      { skuId: "sku-bp-premium", skuName: "Premium Battle Pass", count: 1, totalSpent: 19.99 },
    ],
    activityLog: [
      { date: daysAgoISO(0), action: "Login", detail: "Web store session" },
      { date: daysAgoISO(1), action: "Purchase", detail: "3,000 Gems ($19.99)" },
      { date: daysAgoISO(3), action: "Purchase", detail: "VIP Monthly ($4.99)" },
      { date: daysAgoISO(7), action: "Login", detail: "Web store session" },
    ],
  },
  {
    id: "player-002",
    name: "NovaBlade",
    email: "nova.blade@mail.com",
    status: "active",
    ltv: 847.3,
    aov: 28.24,
    purchaseCount: 30,
    firstPurchaseAt: "2025-08-05",
    lastActiveAt: daysAgo(1),
    createdAt: "2025-07-30",
    country: "JP",
    topItems: [
      { skuId: "sku-gems-1200", skuName: "1,200 Gems", count: 12, totalSpent: 119.88 },
      { skuId: "sku-bp-standard", skuName: "Season 12 Battle Pass", count: 1, totalSpent: 9.99 },
    ],
    activityLog: [
      { date: daysAgoISO(1), action: "Purchase", detail: "1,200 Gems ($9.99)" },
      { date: daysAgoISO(2), action: "Login", detail: "Web store session" },
    ],
  },
  {
    id: "player-003",
    name: "IronFistKai",
    email: "kai.iron@gaming.co",
    status: "active",
    ltv: 534.7,
    aov: 17.82,
    purchaseCount: 30,
    firstPurchaseAt: "2025-09-12",
    lastActiveAt: daysAgo(0),
    createdAt: "2025-09-01",
    country: "US",
    topItems: [
      { skuId: "sku-gems-500", skuName: "500 Gems", count: 15, totalSpent: 74.85 },
      { skuId: "sku-mystery-box", skuName: "Mystery Box", count: 8, totalSpent: 15.92 },
    ],
    activityLog: [
      { date: daysAgoISO(0), action: "Purchase", detail: "500 Gems ($4.99)" },
      { date: daysAgoISO(1), action: "Login", detail: "Web store session" },
    ],
  },
  {
    id: "player-004",
    name: "SakuraMoon",
    email: "sakura.moon@jp.co",
    status: "active",
    ltv: 321.4,
    aov: 32.14,
    purchaseCount: 10,
    firstPurchaseAt: "2025-10-01",
    lastActiveAt: daysAgo(2),
    createdAt: "2025-09-25",
    country: "JP",
    topItems: [
      { skuId: "sku-dragon-skin", skuName: "Dragon Skin", count: 1, totalSpent: 3.99 },
      { skuId: "sku-gems-1200", skuName: "1,200 Gems", count: 5, totalSpent: 49.95 },
    ],
    activityLog: [
      { date: daysAgoISO(2), action: "Purchase", detail: "Dragon Skin ($3.99)" },
      { date: daysAgoISO(5), action: "Login", detail: "Web store session" },
    ],
  },
  {
    id: "player-005",
    name: "PixelWitch",
    email: "pixelwitch@outlook.com",
    status: "active",
    ltv: 189.5,
    aov: 9.47,
    purchaseCount: 20,
    firstPurchaseAt: "2025-10-20",
    lastActiveAt: daysAgo(1),
    createdAt: "2025-10-15",
    country: "DE",
    topItems: [
      { skuId: "sku-gems-500", skuName: "500 Gems", count: 10, totalSpent: 49.9 },
      { skuId: "sku-gold-weekly", skuName: "Gold Pass Weekly", count: 6, totalSpent: 11.94 },
    ],
    activityLog: [
      { date: daysAgoISO(1), action: "Purchase", detail: "Gold Pass Weekly ($1.99)" },
    ],
  },
  {
    id: "player-006",
    name: "TurboRex",
    email: "turborex@gmail.com",
    status: "active",
    ltv: 156.8,
    aov: 15.68,
    purchaseCount: 10,
    firstPurchaseAt: "2025-11-02",
    lastActiveAt: daysAgo(3),
    createdAt: "2025-10-28",
    country: "BR",
    topItems: [
      { skuId: "sku-starter-bundle", skuName: "Starter Bundle", count: 1, totalSpent: 2.99 },
      { skuId: "sku-gems-500", skuName: "500 Gems", count: 8, totalSpent: 39.92 },
    ],
    activityLog: [
      { date: daysAgoISO(3), action: "Login", detail: "Web store session" },
    ],
  },
  {
    id: "player-007",
    name: "GhostArrow",
    email: "ghost.arrow@proton.me",
    status: "active",
    ltv: 112.4,
    aov: 14.05,
    purchaseCount: 8,
    firstPurchaseAt: "2025-11-15",
    lastActiveAt: daysAgo(0),
    createdAt: "2025-11-10",
    country: "US",
    topItems: [
      { skuId: "sku-neon-shield", skuName: "Neon Shield", count: 1, totalSpent: 2.49 },
      { skuId: "sku-gems-500", skuName: "500 Gems", count: 5, totalSpent: 24.95 },
    ],
    activityLog: [
      { date: daysAgoISO(0), action: "Login", detail: "Web store session" },
      { date: daysAgoISO(1), action: "Purchase", detail: "Neon Shield ($2.49)" },
    ],
  },
  {
    id: "player-008",
    name: "CrimsonViper",
    email: "crimson.v@hotmail.com",
    status: "banned",
    ltv: 87.3,
    aov: 43.65,
    purchaseCount: 2,
    firstPurchaseAt: "2025-12-01",
    lastActiveAt: daysAgo(14),
    createdAt: "2025-11-28",
    country: "US",
    topItems: [
      { skuId: "sku-gems-3000", skuName: "3,000 Gems", count: 2, totalSpent: 39.98 },
    ],
    activityLog: [
      { date: daysAgoISO(14), action: "Banned", detail: "Suspicious payment pattern" },
      { date: daysAgoISO(15), action: "Purchase", detail: "3,000 Gems ($19.99)" },
      { date: daysAgoISO(15), action: "Purchase", detail: "3,000 Gems ($19.99)" },
    ],
  },
  {
    id: "player-009",
    name: "LunaFrost",
    email: "luna.frost@icloud.com",
    status: "active",
    ltv: 76.9,
    aov: 12.82,
    purchaseCount: 6,
    firstPurchaseAt: "2025-12-10",
    lastActiveAt: daysAgo(1),
    createdAt: "2025-12-05",
    country: "GB",
    topItems: [
      { skuId: "sku-gems-500", skuName: "500 Gems", count: 4, totalSpent: 19.96 },
      { skuId: "sku-shadow-wings", skuName: "Shadow Wings", count: 1, totalSpent: 5.99 },
    ],
    activityLog: [
      { date: daysAgoISO(1), action: "Purchase", detail: "Shadow Wings ($5.99)" },
    ],
  },
  {
    id: "player-010",
    name: "BlazeStar",
    email: "blazestar@yahoo.com",
    status: "active",
    ltv: 64.5,
    aov: 10.75,
    purchaseCount: 6,
    firstPurchaseAt: "2025-12-20",
    lastActiveAt: daysAgo(2),
    createdAt: "2025-12-18",
    country: "IN",
    topItems: [
      { skuId: "sku-starter-bundle", skuName: "Starter Bundle", count: 1, totalSpent: 2.99 },
      { skuId: "sku-gems-100", skuName: "100 Gems", count: 3, totalSpent: 2.97 },
    ],
    activityLog: [
      { date: daysAgoISO(2), action: "Purchase", detail: "100 Gems ($0.99)" },
    ],
  },
  {
    id: "player-011",
    name: "ZeroGravity",
    email: "zero.g@gmail.com",
    status: "active",
    ltv: 52.3,
    aov: 8.72,
    purchaseCount: 6,
    firstPurchaseAt: "2026-01-05",
    lastActiveAt: daysAgo(0),
    createdAt: "2026-01-02",
    country: "US",
    topItems: [
      { skuId: "sku-gems-500", skuName: "500 Gems", count: 4, totalSpent: 19.96 },
    ],
    activityLog: [
      { date: daysAgoISO(0), action: "Login", detail: "Web store session" },
    ],
  },
  {
    id: "player-012",
    name: "ArcticWolf",
    email: "arctic.wolf@mail.de",
    status: "active",
    ltv: 45.8,
    aov: 11.45,
    purchaseCount: 4,
    firstPurchaseAt: "2026-01-10",
    lastActiveAt: daysAgo(4),
    createdAt: "2026-01-08",
    country: "DE",
    topItems: [
      { skuId: "sku-warrior-pack", skuName: "Warrior Starter Pack", count: 1, totalSpent: 7.99 },
      { skuId: "sku-gems-500", skuName: "500 Gems", count: 2, totalSpent: 9.98 },
    ],
    activityLog: [
      { date: daysAgoISO(4), action: "Purchase", detail: "Warrior Starter Pack ($7.99)" },
    ],
  },
  {
    id: "player-013",
    name: "SilverStrike",
    email: "silverstrike@outlook.jp",
    status: "active",
    ltv: 38.9,
    aov: 9.73,
    purchaseCount: 4,
    firstPurchaseAt: "2026-01-15",
    lastActiveAt: daysAgo(1),
    createdAt: "2026-01-12",
    country: "JP",
    topItems: [
      { skuId: "sku-bp-standard", skuName: "Season 12 Battle Pass", count: 1, totalSpent: 9.99 },
      { skuId: "sku-gems-100", skuName: "100 Gems", count: 5, totalSpent: 4.95 },
    ],
    activityLog: [
      { date: daysAgoISO(1), action: "Purchase", detail: "100 Gems ($0.99)" },
    ],
  },
  {
    id: "player-014",
    name: "EmberPhoenix",
    email: "ember.ph@gmail.com",
    status: "active",
    ltv: 29.9,
    aov: 7.48,
    purchaseCount: 4,
    firstPurchaseAt: "2026-01-20",
    lastActiveAt: daysAgo(3),
    createdAt: "2026-01-18",
    country: "BR",
    topItems: [
      { skuId: "sku-mystery-box", skuName: "Mystery Box", count: 3, totalSpent: 5.97 },
    ],
    activityLog: [
      { date: daysAgoISO(3), action: "Purchase", detail: "Mystery Box ($1.99)" },
    ],
  },
  {
    id: "player-015",
    name: "NightRaven",
    email: "nightraven@proton.me",
    status: "active",
    ltv: 22.4,
    aov: 5.6,
    purchaseCount: 4,
    firstPurchaseAt: "2026-01-25",
    lastActiveAt: daysAgo(5),
    createdAt: "2026-01-22",
    country: "GB",
    topItems: [
      { skuId: "sku-gems-100", skuName: "100 Gems", count: 4, totalSpent: 3.96 },
      { skuId: "sku-gold-weekly", skuName: "Gold Pass Weekly", count: 2, totalSpent: 3.98 },
    ],
    activityLog: [
      { date: daysAgoISO(5), action: "Login", detail: "Web store session" },
    ],
  },
  {
    id: "player-016",
    name: "CosmicDust",
    email: "cosmic.dust@yahoo.co.in",
    status: "active",
    ltv: 17.9,
    aov: 8.95,
    purchaseCount: 2,
    firstPurchaseAt: "2026-02-01",
    lastActiveAt: daysAgo(1),
    createdAt: "2026-01-28",
    country: "IN",
    topItems: [
      { skuId: "sku-starter-bundle", skuName: "Starter Bundle", count: 1, totalSpent: 2.99 },
      { skuId: "sku-gems-500", skuName: "500 Gems", count: 1, totalSpent: 4.99 },
    ],
    activityLog: [
      { date: daysAgoISO(1), action: "Purchase", detail: "500 Gems ($4.99)" },
    ],
  },
  {
    id: "player-017",
    name: "StormChaser",
    email: "stormchaser@live.com",
    status: "active",
    ltv: 12.97,
    aov: 4.32,
    purchaseCount: 3,
    firstPurchaseAt: "2026-02-05",
    lastActiveAt: daysAgo(0),
    createdAt: "2026-02-02",
    country: "US",
    topItems: [
      { skuId: "sku-gems-100", skuName: "100 Gems", count: 3, totalSpent: 2.97 },
    ],
    activityLog: [
      { date: daysAgoISO(0), action: "Purchase", detail: "100 Gems ($0.99)" },
    ],
  },
  {
    id: "player-018",
    name: "VoidWalker",
    email: "voidwalker@mail.com",
    status: "banned",
    ltv: 8.97,
    aov: 2.99,
    purchaseCount: 3,
    firstPurchaseAt: "2026-02-08",
    lastActiveAt: daysAgo(7),
    createdAt: "2026-02-06",
    country: "US",
    topItems: [
      { skuId: "sku-mystery-box", skuName: "Mystery Box", count: 3, totalSpent: 5.97 },
    ],
    activityLog: [
      { date: daysAgoISO(7), action: "Banned", detail: "Chargeback abuse" },
      { date: daysAgoISO(8), action: "Purchase", detail: "Mystery Box ($1.99)" },
    ],
  },
  {
    id: "player-019",
    name: "ThunderBolt",
    email: "thunderbolt@gmail.com",
    status: "active",
    ltv: 5.98,
    aov: 2.99,
    purchaseCount: 2,
    firstPurchaseAt: "2026-02-12",
    lastActiveAt: daysAgo(2),
    createdAt: "2026-02-10",
    country: "JP",
    topItems: [
      { skuId: "sku-gems-100", skuName: "100 Gems", count: 2, totalSpent: 1.98 },
    ],
    activityLog: [
      { date: daysAgoISO(2), action: "Purchase", detail: "100 Gems ($0.99)" },
    ],
  },
  {
    id: "player-020",
    name: "SkyPirate",
    email: "skypirate@hotmail.com",
    status: "active",
    ltv: 2.99,
    aov: 2.99,
    purchaseCount: 1,
    firstPurchaseAt: daysAgo(1),
    lastActiveAt: daysAgo(0),
    createdAt: daysAgo(3),
    country: "BR",
    topItems: [
      { skuId: "sku-starter-bundle", skuName: "Starter Bundle", count: 1, totalSpent: 2.99 },
    ],
    activityLog: [
      { date: daysAgoISO(1), action: "Purchase", detail: "Starter Bundle ($2.99)" },
      { date: daysAgoISO(3), action: "Account Created", detail: "Registered via web store" },
    ],
  },
];

// ── Transactions (50) ──

const txStatuses: Array<"completed" | "pending" | "refunded" | "cancelled" | "failed"> = [
  "completed", "completed", "completed", "completed", "completed",
  "completed", "completed", "completed", "pending", "refunded",
];
const payMethods = ["credit_card", "google_pay", "apple_pay", "credit_card", "credit_card"];
const devices = ["iOS", "Android", "Web", "iOS", "Android"];

function makeTx(
  idx: number,
  playerId: string,
  playerName: string,
  skuId: string,
  skuName: string,
  amount: number,
  day: number,
  statusOverride?: "completed" | "pending" | "refunded" | "cancelled" | "failed"
): Transaction {
  const status = statusOverride ?? txStatuses[idx % txStatuses.length];
  const created = daysAgoISO(day);
  return {
    id: `tx-${String(idx + 1).padStart(4, "0")}`,
    playerId,
    playerName,
    skuId,
    skuName,
    amount,
    currency: "USD",
    status,
    paymentMethod: payMethods[idx % payMethods.length],
    createdAt: created,
    settledAt: status === "completed" ? daysAgo(Math.max(0, day - 1)) : undefined,
    refundedAt: status === "refunded" ? daysAgo(Math.max(0, day - 2)) : undefined,
    gatewayRef: `gw_${Math.random().toString(36).slice(2, 14)}`,
    ipAddress: `${72 + (idx % 30)}.${100 + (idx % 55)}.${idx % 256}.${(idx * 7) % 256}`,
    deviceType: devices[idx % devices.length],
    settlementAmount: status === "completed" ? +(amount * 0.92).toFixed(2) : undefined,
    fees: status === "completed" ? +(amount * 0.08).toFixed(2) : undefined,
  };
}

export const MOCK_TRANSACTIONS: Transaction[] = [
  makeTx(0, "player-001", "DragonSlayer99", "sku-gems-3000", "3,000 Gems", 19.99, 1),
  makeTx(1, "player-002", "NovaBlade", "sku-gems-1200", "1,200 Gems", 9.99, 1),
  makeTx(2, "player-003", "IronFistKai", "sku-gems-500", "500 Gems", 4.99, 1),
  makeTx(3, "player-007", "GhostArrow", "sku-neon-shield", "Neon Shield", 2.49, 1),
  makeTx(4, "player-001", "DragonSlayer99", "sku-vip-monthly", "VIP Monthly", 4.99, 2),
  makeTx(5, "player-005", "PixelWitch", "sku-gold-weekly", "Gold Pass Weekly", 1.99, 2),
  makeTx(6, "player-011", "ZeroGravity", "sku-gems-500", "500 Gems", 4.99, 2),
  makeTx(7, "player-009", "LunaFrost", "sku-shadow-wings", "Shadow Wings", 5.99, 3),
  makeTx(8, "player-004", "SakuraMoon", "sku-dragon-skin", "Dragon Skin", 3.99, 3, "pending"),
  makeTx(9, "player-017", "StormChaser", "sku-gems-100", "100 Gems", 0.99, 3),
  makeTx(10, "player-001", "DragonSlayer99", "sku-gems-3000", "3,000 Gems", 19.99, 4),
  makeTx(11, "player-006", "TurboRex", "sku-gems-500", "500 Gems", 4.99, 4),
  makeTx(12, "player-003", "IronFistKai", "sku-mystery-box", "Mystery Box", 1.99, 4),
  makeTx(13, "player-014", "EmberPhoenix", "sku-mystery-box", "Mystery Box", 1.99, 5),
  makeTx(14, "player-015", "NightRaven", "sku-gold-weekly", "Gold Pass Weekly", 1.99, 5),
  makeTx(15, "player-002", "NovaBlade", "sku-bp-standard", "Season 12 Battle Pass", 9.99, 5),
  makeTx(16, "player-010", "BlazeStar", "sku-gems-100", "100 Gems", 0.99, 6),
  makeTx(17, "player-012", "ArcticWolf", "sku-warrior-pack", "Warrior Starter Pack", 7.99, 6),
  makeTx(18, "player-001", "DragonSlayer99", "sku-bp-premium", "Premium Battle Pass", 19.99, 7),
  makeTx(19, "player-016", "CosmicDust", "sku-gems-500", "500 Gems", 4.99, 7),
  makeTx(20, "player-008", "CrimsonViper", "sku-gems-3000", "3,000 Gems", 19.99, 8, "refunded"),
  makeTx(21, "player-005", "PixelWitch", "sku-gems-500", "500 Gems", 4.99, 8),
  makeTx(22, "player-013", "SilverStrike", "sku-bp-standard", "Season 12 Battle Pass", 9.99, 9),
  makeTx(23, "player-003", "IronFistKai", "sku-gems-500", "500 Gems", 4.99, 9),
  makeTx(24, "player-019", "ThunderBolt", "sku-gems-100", "100 Gems", 0.99, 10),
  makeTx(25, "player-001", "DragonSlayer99", "sku-gems-3000", "3,000 Gems", 19.99, 10),
  makeTx(26, "player-020", "SkyPirate", "sku-starter-bundle", "Starter Bundle", 2.99, 11),
  makeTx(27, "player-007", "GhostArrow", "sku-gems-500", "500 Gems", 4.99, 11),
  makeTx(28, "player-004", "SakuraMoon", "sku-gems-1200", "1,200 Gems", 9.99, 12),
  makeTx(29, "player-002", "NovaBlade", "sku-gems-1200", "1,200 Gems", 9.99, 12),
  makeTx(30, "player-006", "TurboRex", "sku-gems-500", "500 Gems", 4.99, 13),
  makeTx(31, "player-011", "ZeroGravity", "sku-gems-500", "500 Gems", 4.99, 14),
  makeTx(32, "player-005", "PixelWitch", "sku-gems-500", "500 Gems", 4.99, 15),
  makeTx(33, "player-018", "VoidWalker", "sku-mystery-box", "Mystery Box", 1.99, 15, "refunded"),
  makeTx(34, "player-001", "DragonSlayer99", "sku-gems-3000", "3,000 Gems", 19.99, 16),
  makeTx(35, "player-003", "IronFistKai", "sku-gems-500", "500 Gems", 4.99, 17),
  makeTx(36, "player-009", "LunaFrost", "sku-gems-500", "500 Gems", 4.99, 18),
  makeTx(37, "player-013", "SilverStrike", "sku-gems-100", "100 Gems", 0.99, 19),
  makeTx(38, "player-010", "BlazeStar", "sku-starter-bundle", "Starter Bundle", 2.99, 20),
  makeTx(39, "player-002", "NovaBlade", "sku-gems-1200", "1,200 Gems", 9.99, 21),
  makeTx(40, "player-014", "EmberPhoenix", "sku-mystery-box", "Mystery Box", 1.99, 22),
  makeTx(41, "player-001", "DragonSlayer99", "sku-gems-3000", "3,000 Gems", 19.99, 23),
  makeTx(42, "player-008", "CrimsonViper", "sku-gems-3000", "3,000 Gems", 19.99, 24, "cancelled"),
  makeTx(43, "player-015", "NightRaven", "sku-gems-100", "100 Gems", 0.99, 24),
  makeTx(44, "player-005", "PixelWitch", "sku-gold-weekly", "Gold Pass Weekly", 1.99, 25),
  makeTx(45, "player-007", "GhostArrow", "sku-gems-500", "500 Gems", 4.99, 26),
  makeTx(46, "player-012", "ArcticWolf", "sku-gems-500", "500 Gems", 4.99, 27),
  makeTx(47, "player-004", "SakuraMoon", "sku-gems-1200", "1,200 Gems", 9.99, 28),
  makeTx(48, "player-006", "TurboRex", "sku-gems-500", "500 Gems", 4.99, 29),
  makeTx(49, "player-011", "ZeroGravity", "sku-gems-500", "500 Gems", 4.99, 30),
];

// ── KPIs ──

export const MOCK_STORE_KPIS: StoreKPI = {
  grossRevenue: 48230,
  grossRevenueChange: 12.4,
  transactions: 1247,
  transactionsChange: 8.1,
  arpu: 12.4,
  arpuChange: 3.2,
  aov: 38.67,
  aovChange: -1.5,
  refunds: 23,
  refundsChange: -15.4,
};

// ── Revenue Chart (30 days) ──

export const MOCK_REVENUE_CHART: RevenueDataPoint[] = Array.from({ length: 30 }, (_, i) => {
  const day = 29 - i;
  const base = 1200 + Math.sin(i * 0.4) * 400;
  const noise = (Math.random() - 0.5) * 300;
  const revenue = Math.round((base + noise) * 100) / 100;
  const txCount = Math.round(revenue / 38 + (Math.random() - 0.5) * 5);
  return {
    date: daysAgo(day),
    revenue: Math.max(600, revenue),
    transactions: Math.max(10, txCount),
  };
});

// ── Offers (8) ──

export const MOCK_OFFERS: Offer[] = [
  {
    id: "offer-001",
    name: "JP Gem Boost",
    skuId: "sku-gems-1200",
    skuName: "1,200 Gems",
    type: "discount_percentage",
    value: 15,
    audienceType: "segment",
    audienceValue: "JP Players",
    startDate: daysAgo(3),
    endDate: daysAgo(-14),
    status: "active",
    campaignId: "camp-001",
    createdAt: daysAgo(4),
    createdBy: "sentinel",
    performance: { views: 312, conversions: 58, revenue: 521.82, dailyRevenue: dailyRevenue(521.82, "up") },
  },
  {
    id: "offer-002",
    name: "JP Battle Pass Deal",
    skuId: "sku-bp-standard",
    skuName: "Season 12 Battle Pass",
    type: "discount_fixed",
    value: 2,
    audienceType: "segment",
    audienceValue: "JP Players",
    startDate: daysAgo(5),
    endDate: daysAgo(-12),
    status: "active",
    campaignId: "camp-001",
    createdAt: daysAgo(6),
    createdBy: "manual",
    performance: { views: 189, conversions: 24, revenue: 191.76, dailyRevenue: dailyRevenue(191.76, "flat") },
  },
  {
    id: "offer-003",
    name: "New Player Welcome",
    skuId: "sku-starter-bundle",
    skuName: "Starter Bundle",
    type: "discount_percentage",
    value: 30,
    audienceType: "segment",
    audienceValue: "New Players",
    startDate: daysAgo(1),
    endDate: daysAgo(-29),
    status: "active",
    campaignId: "camp-002",
    createdAt: daysAgo(2),
    createdBy: "sentinel",
    performance: { views: 87, conversions: 12, revenue: 25.08, dailyRevenue: dailyRevenue(25.08, "up") },
  },
  {
    id: "offer-004",
    name: "Weekend Gem Rush",
    skuId: "sku-gems-500",
    skuName: "500 Gems",
    type: "discount_percentage",
    value: 20,
    audienceType: "all",
    startDate: daysAgo(-2),
    endDate: daysAgo(-4),
    status: "scheduled",
    createdAt: daysAgo(1),
    createdBy: "manual",
    performance: { views: 0, conversions: 0, revenue: 0, dailyRevenue: dailyRevenue(0) },
  },
  {
    id: "offer-005",
    name: "Whale Appreciation",
    skuId: "sku-gems-3000",
    skuName: "3,000 Gems",
    type: "price_override",
    value: 16.99,
    audienceType: "segment",
    audienceValue: "High LTV Players",
    startDate: daysAgo(20),
    endDate: daysAgo(5),
    status: "expired",
    createdAt: daysAgo(22),
    createdBy: "sentinel",
    performance: { views: 45, conversions: 8, revenue: 135.92, dailyRevenue: dailyRevenue(135.92, "down") },
  },
  {
    id: "offer-006",
    name: "Dragon Skin Flash Sale",
    skuId: "sku-dragon-skin",
    skuName: "Dragon Skin",
    type: "discount_percentage",
    value: 25,
    audienceType: "all",
    startDate: daysAgo(2),
    endDate: daysAgo(-5),
    status: "paused",
    createdAt: daysAgo(3),
    createdBy: "manual",
    performance: { views: 134, conversions: 18, revenue: 53.82, dailyRevenue: dailyRevenue(53.82, "spike") },
  },
  {
    id: "offer-007",
    name: "Mystery Box BOGO",
    skuId: "sku-mystery-box",
    skuName: "Mystery Box",
    type: "bundle_deal",
    value: 50,
    audienceType: "all",
    startDate: daysAgo(0),
    endDate: daysAgo(-7),
    status: "draft",
    createdAt: daysAgo(0),
    createdBy: "manual",
    performance: { views: 0, conversions: 0, revenue: 0, dailyRevenue: dailyRevenue(0) },
  },
  {
    id: "offer-008",
    name: "VIP Trial Discount",
    skuId: "sku-vip-monthly",
    skuName: "VIP Monthly",
    type: "discount_percentage",
    value: 40,
    audienceType: "segment",
    audienceValue: "Lapsed Players",
    startDate: daysAgo(10),
    endDate: daysAgo(-4),
    status: "active",
    createdAt: daysAgo(12),
    createdBy: "sentinel",
    performance: { views: 201, conversions: 31, revenue: 92.69, dailyRevenue: dailyRevenue(92.69, "flat") },
  },
];

// ── Campaigns (2) ──

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: "camp-001",
    name: "Q1 JP Re-engagement",
    description: "Win back lapsed Japanese players with localized gem discounts",
    goal: "Increase JP revenue by 20%",
    status: "active",
    offerIds: ["offer-001", "offer-002"],
    startDate: daysAgo(7),
    endDate: daysAgo(-23),
    createdAt: daysAgo(8),
  },
  {
    id: "camp-002",
    name: "New Player Onboarding",
    description: "First-purchase discount for players registered in last 7 days",
    goal: "Increase new player conversion rate",
    status: "active",
    offerIds: ["offer-003"],
    startDate: daysAgo(1),
    endDate: daysAgo(-29),
    createdAt: daysAgo(2),
  },
];
