import { render } from "@react-email/render";
import {
  Body,
  Container,
  Font,
  Head,
  Heading,
  Html,
  Hr,
  Link,
  Preview,
  Section,
  Text,
} from "@react-email/components";
import type { ChartSpec } from "@/lib/chart-types";
import { buildPlaybookOutputMarkdown } from "@/lib/playbook-output-markdown";
import type { PlaybookRunHistory, PlaybookV2 } from "@/lib/playbook-types";

const TABLE_STYLE = "width:100%;border-collapse:collapse;margin:16px 0;font-size:13px;line-height:1.45";
const TH_STYLE = "border:1px solid #e5e5e5;padding:8px;text-align:left;background:#f7f7f7;font-weight:600";
const TD_STYLE = "border:1px solid #e5e5e5;padding:8px;text-align:left;vertical-align:top";
const CHART_CARD_STYLE = "border:1px solid #e5e5e5;border-radius:6px;padding:14px;margin:18px 0;background:#ffffff";
const CHART_TITLE_STYLE = "font-size:15px;line-height:1.35;margin:0 0 12px;font-weight:700;color:#111111";

export interface RenderPlaybookEmailInput {
  playbook: PlaybookV2;
  run: PlaybookRunHistory;
  subject: string;
}

export async function renderPlaybookOutputEmail(input: RenderPlaybookEmailInput): Promise<{
  html: string;
  markdown: string;
  bodyHtml: string;
}> {
  const markdown = buildPlaybookOutputMarkdown(input.playbook, input.run);
  const bodyHtml = markdownToEmailHtml(markdown);

  const html = await render(
    <FixedPlaybookEmail
      preheader={input.playbook.description}
      headline={input.subject}
      subhead={input.playbook.name}
      bodyHtml={bodyHtml}
    />,
    { pretty: false },
  );
  return { html, markdown, bodyHtml };
}

function FixedPlaybookEmail(props: {
  preheader: string;
  headline: string;
  subhead: string;
  bodyHtml: string;
}) {
  return (
    <Html>
      <Head>
        <Font
          fontFamily="Inter"
          fallbackFontFamily="Helvetica"
          webFont={{
            url: "https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMa1ZL7.woff2",
            format: "woff2",
          }}
          fontWeight={400}
          fontStyle="normal"
        />
      </Head>
      <Preview>{props.preheader}</Preview>
      <Body style={{ backgroundColor: "#f5f5f5", margin: 0, padding: 0 }}>
        <Container
          style={{
            width: "560px",
            maxWidth: "560px",
            margin: "0 auto",
            padding: "32px 0",
            boxSizing: "border-box",
          }}
        >
          <Section
            style={{
              backgroundColor: "#ffffff",
              padding: "48px 40px",
              borderRadius: 12,
            }}
          >
            <Text
              style={{
                color: "#666666",
                fontFamily: "'Inter', Helvetica, sans-serif",
                fontSize: 11.7,
                fontWeight: 600,
                letterSpacing: "0.06em",
                textTransform: "uppercase",
                margin: "0 0 24px",
              }}
            >
              Actioneer
            </Text>
            <Heading
              as="h1"
              style={{
                color: "#111111",
                fontFamily: "'Inter', Helvetica, sans-serif",
                fontSize: 28.8,
                lineHeight: "1.2",
                letterSpacing: "0",
                margin: "0 0 16px",
                fontWeight: 700,
              }}
            >
              {props.headline}
            </Heading>
            <Text
              style={{
                color: "#666666",
                fontFamily: "'Inter', Helvetica, sans-serif",
                fontSize: 14.4,
                lineHeight: "1.6",
                margin: "0 0 24px",
              }}
            >
              {props.subhead}
            </Text>
            <div
              style={{
                color: "#111111",
                fontFamily: "'Inter', Helvetica, sans-serif",
                fontSize: 13.5,
                lineHeight: "1.65",
                margin: "0 0 32px",
              }}
              dangerouslySetInnerHTML={{ __html: props.bodyHtml }}
            />
            <Hr style={{ borderColor: "#e5e5e5", margin: "32px 0 20px" }} />
            <Text
              style={{
                color: "#666666",
                fontFamily: "'Inter', Helvetica, sans-serif",
                fontSize: 10.8,
                lineHeight: "1.5",
                margin: 0,
              }}
            >
              Generated by Actioneer ·{" "}
              <Link href="#" style={{ color: "#666666", textDecoration: "underline" }}>
                Unsubscribe
              </Link>
            </Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
}

export function markdownToEmailHtml(markdown: string): string {
  const lines = markdown.split(/\r?\n/);
  const html: string[] = [];

  for (let i = 0; i < lines.length;) {
    const line = lines[i];
    const trimmed = line.trim();

    if (!trimmed) {
      i += 1;
      continue;
    }

    if (/^```chart\b/i.test(trimmed)) {
      const chartJson: string[] = [];
      i += 1;
      while (i < lines.length && !lines[i].trim().startsWith("```")) {
        chartJson.push(lines[i]);
        i += 1;
      }
      if (i < lines.length) i += 1;
      html.push(renderEmailChart(chartJson.join("\n")));
      continue;
    }

    if (trimmed.startsWith("```")) {
      const code: string[] = [];
      i += 1;
      while (i < lines.length && !lines[i].trim().startsWith("```")) {
        code.push(lines[i]);
        i += 1;
      }
      if (i < lines.length) i += 1;
      if (code.length > 0) {
        html.push(`<pre style="white-space:pre-wrap;background:#f7f7f7;border:1px solid #e5e5e5;padding:12px;border-radius:4px">${escapeHtml(code.join("\n"))}</pre>`);
      }
      continue;
    }

    if (isTableStart(lines, i)) {
      const tableLines: string[] = [];
      while (i < lines.length && lines[i].includes("|")) {
        tableLines.push(lines[i]);
        i += 1;
      }
      html.push(renderMarkdownTable(tableLines));
      continue;
    }

    if (trimmed.startsWith("### ")) {
      html.push(`<h3 style="font-size:16px;line-height:1.35;margin:22px 0 8px">${inlineMarkdown(trimmed.slice(4))}</h3>`);
      i += 1;
      continue;
    }

    if (trimmed.startsWith("## ")) {
      html.push(`<h2 style="font-size:20px;line-height:1.3;margin:28px 0 10px">${inlineMarkdown(trimmed.slice(3))}</h2>`);
      i += 1;
      continue;
    }

    if (trimmed.startsWith("# ")) {
      html.push(`<h1 style="font-size:24px;line-height:1.25;margin:28px 0 12px">${inlineMarkdown(trimmed.slice(2))}</h1>`);
      i += 1;
      continue;
    }

    if (/^[-*]\s+/.test(trimmed)) {
      const items: string[] = [];
      while (i < lines.length && /^[-*]\s+/.test(lines[i].trim())) {
        items.push(`<li style="margin:0 0 6px">${inlineMarkdown(lines[i].trim().replace(/^[-*]\s+/, ""))}</li>`);
        i += 1;
      }
      html.push(`<ul style="margin:12px 0 16px;padding-left:20px">${items.join("")}</ul>`);
      continue;
    }

    if (/^\d+\.\s+/.test(trimmed)) {
      const items: string[] = [];
      while (i < lines.length && /^\d+\.\s+/.test(lines[i].trim())) {
        items.push(`<li style="margin:0 0 6px">${inlineMarkdown(lines[i].trim().replace(/^\d+\.\s+/, ""))}</li>`);
        i += 1;
      }
      html.push(`<ol style="margin:12px 0 16px;padding-left:20px">${items.join("")}</ol>`);
      continue;
    }

    const paragraph: string[] = [trimmed];
    i += 1;
    while (
      i < lines.length &&
      lines[i].trim() &&
      !lines[i].trim().startsWith("#") &&
      !lines[i].trim().startsWith("```") &&
      !isTableStart(lines, i) &&
      !/^[-*]\s+/.test(lines[i].trim()) &&
      !/^\d+\.\s+/.test(lines[i].trim())
    ) {
      paragraph.push(lines[i].trim());
      i += 1;
    }
    html.push(`<p style="margin:0 0 14px;line-height:1.65">${inlineMarkdown(paragraph.join(" "))}</p>`);
  }

  return html.join("\n");
}

function renderEmailChart(jsonText: string): string {
  let spec: ChartSpec;
  try {
    spec = JSON.parse(jsonText) as ChartSpec;
  } catch {
    return `<p style="margin:0 0 14px;line-height:1.65"><strong>Chart:</strong> included in playbook output</p>`;
  }

  const title = spec.title?.trim() || "Chart";
  const data = Array.isArray(spec.data) ? spec.data.slice(0, 8) : [];
  if (data.length === 0) {
    return `<p style="margin:0 0 14px;line-height:1.65"><strong>Chart:</strong> ${escapeHtml(title)}</p>`;
  }

  const xKey = spec.xKey ?? spec.nameKey ?? "label";
  const yKeys = spec.yKeys?.length ? spec.yKeys : [spec.valueKey ?? "value"];
  const rows = data.flatMap((datum) => yKeys.map((yKey, seriesIndex) => {
    const rawValue = datum[yKey];
    const numericValue = typeof rawValue === "number" ? rawValue : Number(rawValue);
    const xValue = datum[xKey] ?? datum.label ?? datum.name ?? "";
    const seriesLabel = spec.yLabels?.[seriesIndex] ?? yKey;
    return {
      label: yKeys.length > 1 ? `${String(xValue)} · ${seriesLabel}` : String(xValue),
      value: Number.isFinite(numericValue) ? numericValue : 0,
      formatted: formatChartValue(numericValue, spec.format?.[yKey], seriesLabel),
    };
  }));

  const max = Math.max(...rows.map((row) => Math.abs(row.value)), 0);
  if (max === 0) {
    return `<p style="margin:0 0 14px;line-height:1.65"><strong>Chart:</strong> ${escapeHtml(title)}</p>`;
  }

  const body = rows.map((row) => {
    const width = Math.max(3, Math.round((Math.abs(row.value) / max) * 100));
    return [
      "<tr>",
      `<td style="padding:6px 8px 6px 0;width:34%;font-size:12px;line-height:1.35;color:#333333;vertical-align:middle">${escapeHtml(row.label)}</td>`,
      `<td style="padding:6px 8px 6px 0;width:43%;vertical-align:middle"><div style="height:12px;background:#eeeeee;border-radius:2px;overflow:hidden"><div style="height:12px;width:${width}%;background:#111111;border-radius:2px"></div></div></td>`,
      `<td style="padding:6px 0;width:23%;font-size:12px;line-height:1.35;color:#111111;text-align:right;vertical-align:middle;font-variant-numeric:tabular-nums">${escapeHtml(row.formatted)}</td>`,
      "</tr>",
    ].join("");
  }).join("");

  return [
    `<div style="${CHART_CARD_STYLE}">`,
    `<h3 style="${CHART_TITLE_STYLE}">${escapeHtml(title)}</h3>`,
    `<table role="presentation" cellpadding="0" cellspacing="0" style="width:100%;border-collapse:collapse">${body}</table>`,
    "</div>",
  ].join("");
}

function formatChartValue(
  value: number,
  format: "number" | "currency" | "percent" | undefined,
  label: string,
): string {
  if (!Number.isFinite(value)) return "-";
  if (format === "percent") return `${value.toLocaleString("en-US", { maximumFractionDigits: 2 })}%`;
  if (format === "currency" || label.includes("₹")) {
    return `₹${value.toLocaleString("en-IN", { maximumFractionDigits: 0 })}`;
  }
  return value.toLocaleString("en-US", { maximumFractionDigits: 2 });
}

function isTableStart(lines: string[], index: number): boolean {
  return Boolean(
    lines[index]?.includes("|") &&
    lines[index + 1]?.trim().match(/^\|?[-|:\s]+\|?$/),
  );
}

function renderMarkdownTable(lines: string[]): string {
  const [headerLine, _separator, ...rowLines] = lines;
  const headers = splitTableRow(headerLine);
  const rows = rowLines.map(splitTableRow).filter((row) => row.length > 0);

  return [
    `<table style="${TABLE_STYLE}">`,
    "<thead><tr>",
    ...headers.map((header) => `<th style="${TH_STYLE}">${inlineMarkdown(header)}</th>`),
    "</tr></thead>",
    "<tbody>",
    ...rows.map((row) => [
      "<tr>",
      ...headers.map((_header, index) => `<td style="${TD_STYLE}">${inlineMarkdown(row[index] ?? "")}</td>`),
      "</tr>",
    ].join("")),
    "</tbody></table>",
  ].join("");
}

function splitTableRow(line: string): string[] {
  const trimmed = line.trim().replace(/^\|/, "").replace(/\|$/, "");
  return trimmed.split("|").map((cell) => cell.replace(/\\\|/g, "|").trim());
}

function inlineMarkdown(value: string): string {
  const escaped = escapeHtml(value);
  return escaped
    .replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>")
    .replace(/\[([^\]]+)\]\((https?:\/\/[^)\s]+)\)/g, (_full, label: string, href: string) => {
      const safeHref = escapeHtml(href);
      return `<a href="${safeHref}" style="color:#111111;text-decoration:underline">${label}</a>`;
    });
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
